### ISSUE TITLE
Add Seat support in this library

### ISSUE THREAD

**Issue by DefV** [lendy007/skodaconnect#11]
Hey.

Right now there are different libraries for VWConnect (which you started from), Skodaconnect and Seatconnect (which started from your work). From what I can see the skodaconnect library has been most actively updated, and from small experimentation it seems that just changing `const.py` allows for this library to talk to Seatconnect just as well.

Would it be an idea / option to somehow merge some of the work @Farfar has done on @Farfar/seatconnect with this library to have one library that supports both Seat and Skoda?

The updated const file for Seat is basically this:

```python
"""Constants for Seat Connect library."""

BASE_SESSION = 'https://msg.volkswagen.de'
BASE_AUTH = 'https://identity.vwgroup.io'
BRAND = 'seat'
COUNTRY = 'ES'

# Data used in communication
CLIENT = {
    'Legacy': {
        'CLIENT_ID':    '50f215ac-4444-4230-9fb1-fe15cd1a9bcc@apps_vw-dilab_com',     # client id for VWG API, legacy Skoda Connect/MySkoda
        'SCOPE':        'openid mbb profile cars birthdate nickname address phone',
        'TOKEN_TYPES':  'code id_token'
    }
}

XCLIENT_ID = '3516bc10-fabd-4eb2-b41c-b38e21e9d8f6'
XAPPVERSION = '1.2.0'
XAPPNAME = 'SEATConnect'
USER_AGENT = 'okhttp/3.10.0'
APP_URI = 'seatconnect://identity-kit/login'

# Used when fetching data
HEADERS_SESSION = {
    'Connection': 'keep-alive',
    'Content-Type': 'application/json',
    'Accept-charset': 'UTF-8',
    'Accept': 'application/json',
    'X-Client-Id': XCLIENT_ID,
    'X-App-Version': XAPPVERSION,
    'X-App-Name': XAPPNAME,
    'User-Agent': USER_AGENT,
    'tokentype': 'IDK_TECHNICAL'
}

# Used for authentication
HEADERS_AUTH = {
    'Connection': 'keep-alive',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'Accept-Encoding': 'gzip, deflate',
    'Content-Type': 'application/x-www-form-urlencoded',
    'x-requested-with': XAPPNAME,
    'User-Agent': USER_AGENT,
    'X-App-Name': XAPPNAME
}
```

Thanks for all the work you've put into this so far. It made entering my mileage information for work so much easier ;)

**Comment by Farfar** [comment]
> Hey.
> 
> Right now there are different libraries for VWConnect (which you started from), Skodaconnect and Seatconnect (which started from your work). From what I can see the skodaconnect library has been most actively updated, and from small experimentation it seems that just changing `const.py` allows for this library to talk to Seatconnect just as well.
> 
> Would it be an idea / option to somehow merge some of the work @Farfar has done on @Farfar/seatconnect with this library to have one library that supports both Seat and Skoda?
> 
> The updated const file for Seat is basically this:
> 
> ```python
> """Constants for Seat Connect library."""
> 
> BASE_SESSION = 'https://msg.volkswagen.de'
> BASE_AUTH = 'https://identity.vwgroup.io'
> BRAND = 'seat'
> COUNTRY = 'ES'
> 
> # Data used in communication
> CLIENT = {
>     'Legacy': {
>         'CLIENT_ID':    '50f215ac-4444-4230-9fb1-fe15cd1a9bcc@apps_vw-dilab_com',     # client id for VWG API, legacy Skoda Connect/MySkoda
>         'SCOPE':        'openid mbb profile cars birthdate nickname address phone',
>         'TOKEN_TYPES':  'code id_token'
>     }
> }
> 
> XCLIENT_ID = '3516bc10-fabd-4eb2-b41c-b38e21e9d8f6'
> XAPPVERSION = '1.2.0'
> XAPPNAME = 'SEATConnect'
> USER_AGENT = 'okhttp/3.10.0'
> APP_URI = 'seatconnect://identity-kit/login'
> 
> # Used when fetching data
> HEADERS_SESSION = {
>     'Connection': 'keep-alive',
>     'Content-Type': 'application/json',
>     'Accept-charset': 'UTF-8',
>     'Accept': 'application/json',
>     'X-Client-Id': XCLIENT_ID,
>     'X-App-Version': XAPPVERSION,
>     'X-App-Name': XAPPNAME,
>     'User-Agent': USER_AGENT,
>     'tokentype': 'IDK_TECHNICAL'
> }
> 
> # Used for authentication
> HEADERS_AUTH = {
>     'Connection': 'keep-alive',
>     'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
>     'Accept-Encoding': 'gzip, deflate',
>     'Content-Type': 'application/x-www-form-urlencoded',
>     'x-requested-with': XAPPNAME,
>     'User-Agent': USER_AGENT,
>     'X-App-Name': XAPPNAME
> }
> ```
> 
> Thanks for all the work you've put into this so far. It made entering my mileage information for work so much easier ;)

This was my plan when I coded the Seat integration.
But it seems as if Skoda is moving (maybe, not 100% sure) away from using VW Group central API and moving functions to their own API servers.
For a common integration to work we need a more reliable way to determine API endpoints and enabled functions.

We can reliably logon with different brands and client ids to get an identity token used for centralized API but functionality since february seems to be changing, many changes to login just this past few weeks.
Skoda App now uses 3 different client ids with different functionality, only one works for acquiring a VW-Group API token and not all cars/accounts have this functionality (Skoda/Seat/We Connect).

Some parts of the magic that tells the app what queries are to be made, and how, is missing to make this a smooth and reliable experience.
Someone else is welcome to make it tappen and are free to contact me and I'll help in any way I can. I feel though that my level of goding experience is not enough to make it happen so I won't pursue it further, I will only maintain the skodaconnect integration. The Seat integration I can assume will work the same and might get the same patching done but I have no way of testing since I don't own a Seat.

Hope this makes sense.
